### ISSUE TITLE
2.2 not available?

### ISSUE THREAD

**Issue by knaaptime** [conda-forge/esda-feedstock#6]
Hey @ocefpaf, I'm not sure the best place to raise this, but I see that version 2.2 was [merged](https://github.com/conda-forge/esda-feedstock/pull/5) in december, but for some reason 2.1.1 is the latest version available in the channel? Any ideas?

**Comment by ocefpaf** [comment]
> Hey @ocefpaf, I'm not sure the best place to raise this

The issue here is fine.

> but I see that version 2.2 was [merged](https://github.com/conda-forge/esda-feedstock/pull/5) in december, but for some reason 2.1.1 is the latest version available in the channel? Any ideas?

Looks like the CIs never started on `master`. I'm re-starting them and you can follow it [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=115076&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3), the package should be up ~50 min after the CI is done. Thanks for reporting!

**Comment by knaaptime** [comment]
awesome, thanks!
